version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "eureka"
          ContainerPort: 80
          version: 0.0
hooks:
  BeforeInstall:
    - timeout: 300
  Install:
    - timeout: 300
  AfterInstall:
    - timeout: 300
  ApplicationStart:
    - timeout: 300
  ApplicationStop:
    - timeout: 300

