version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Doing mvn test...
      - mvn test
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - docker build -t eureka .
      - docker tag eureka:latest 687804506828.dkr.ecr.us-east-1.amazonaws.com/eureka:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 687804506828.dkr.ecr.us-east-1.amazonaws.com/eureka:latest
