version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
      - docker build -t eureka .
      - docker tag eureka:latest 687804506828.dkr.ecr.us-east-1.amazonaws.com/eureka:latest
  post_build:
    commands:
      - mvn package
      - echo Build completed on `date`
      - docker push 687804506828.dkr.ecr.us-east-1.amazonaws.com/eureka:latest
